/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MovieNightsIndexRouteImport } from './routes/movie-nights.index'
import { Route as MovieNightsOctoberRouteImport } from './routes/movie-nights/october'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieNightsIndexRoute = MovieNightsIndexRouteImport.update({
  id: '/movie-nights/',
  path: '/movie-nights/',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieNightsOctoberRoute = MovieNightsOctoberRouteImport.update({
  id: '/movie-nights/october',
  path: '/movie-nights/october',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/movie-nights/october': typeof MovieNightsOctoberRoute
  '/movie-nights': typeof MovieNightsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/movie-nights/october': typeof MovieNightsOctoberRoute
  '/movie-nights': typeof MovieNightsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/movie-nights/october': typeof MovieNightsOctoberRoute
  '/movie-nights/': typeof MovieNightsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/movie-nights/october' | '/movie-nights'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/movie-nights/october' | '/movie-nights'
  id: '__root__' | '/' | '/movie-nights/october' | '/movie-nights/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MovieNightsOctoberRoute: typeof MovieNightsOctoberRoute
  MovieNightsIndexRoute: typeof MovieNightsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie-nights/': {
      id: '/movie-nights/'
      path: '/movie-nights'
      fullPath: '/movie-nights'
      preLoaderRoute: typeof MovieNightsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie-nights/october': {
      id: '/movie-nights/october'
      path: '/movie-nights/october'
      fullPath: '/movie-nights/october'
      preLoaderRoute: typeof MovieNightsOctoberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MovieNightsOctoberRoute: MovieNightsOctoberRoute,
  MovieNightsIndexRoute: MovieNightsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
